// Auto-generated by scripts/gen_supabase_types.py — do not edit by hand.
// Regenerate with: python scripts/gen_supabase_types.py

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          display_name: string | null
          cdm_card_no: string | null
          created_at: string
          updated_at: string
        };
        Insert: {
          id: string
          display_name?: string | null
          cdm_card_no?: string | null
          created_at?: string
          updated_at?: string
        };
        Update: {
          id?: string
          display_name?: string | null
          cdm_card_no?: string | null
          created_at?: string
          updated_at?: string
        };
        Relationships: [];
      };
      repertoire: {
        Row: {
          id: string
          user_id: string
          song_id: string
          preferred_key: number
          confidence: Database["public"]["Enums"]["confidence_level"]
          tags: string[]
          memo: string | null
          is_favorite: boolean
          added_at: string
          updated_at: string
        };
        Insert: {
          id?: string
          user_id: string
          song_id: string
          preferred_key?: number
          confidence?: Database["public"]["Enums"]["confidence_level"]
          tags?: string[]
          memo?: string | null
          is_favorite?: boolean
          added_at?: string
          updated_at?: string
        };
        Update: {
          id?: string
          user_id?: string
          song_id?: string
          preferred_key?: number
          confidence?: Database["public"]["Enums"]["confidence_level"]
          tags?: string[]
          memo?: string | null
          is_favorite?: boolean
          added_at?: string
          updated_at?: string
        };
        Relationships: [];
      };
      score_pitch_intervals: {
        Row: {
          score_id: string
          user_id: string
          intervals: number[]
          details: Json | null
          created_at: string
        };
        Insert: {
          score_id: string
          user_id: string
          intervals: number[]
          details?: Json | null
          created_at?: string
        };
        Update: {
          score_id?: string
          user_id?: string
          intervals?: number[]
          details?: Json | null
          created_at?: string
        };
        Relationships: [];
      };
      scores: {
        Row: {
          id: string
          user_id: string
          song_id: string
          session_id: string | null
          scoring_type: Database["public"]["Enums"]["scoring_type"]
          dam_scoring_id: string
          sung_at: string
          total_score: number
          pitch_score: number | null
          stability_score: number | null
          expression_score: number | null
          vibrato_longtone_score: number | null
          rhythm_score: number | null
          ai_bonus: number | null
          key_control: number
          tempo_control: number | null
          guide_melody: boolean | null
          singing_range_lowest: number | null
          singing_range_highest: number | null
          vocal_range_lowest: number | null
          vocal_range_highest: number | null
          raw_xml: Json
          created_at: string
        };
        Insert: {
          id?: string
          user_id: string
          song_id: string
          session_id?: string | null
          scoring_type: Database["public"]["Enums"]["scoring_type"]
          dam_scoring_id: string
          sung_at: string
          total_score: number
          pitch_score?: number | null
          stability_score?: number | null
          expression_score?: number | null
          vibrato_longtone_score?: number | null
          rhythm_score?: number | null
          ai_bonus?: number | null
          key_control?: number
          tempo_control?: number | null
          guide_melody?: boolean | null
          singing_range_lowest?: number | null
          singing_range_highest?: number | null
          vocal_range_lowest?: number | null
          vocal_range_highest?: number | null
          raw_xml: Json
          created_at?: string
        };
        Update: {
          id?: string
          user_id?: string
          song_id?: string
          session_id?: string | null
          scoring_type?: Database["public"]["Enums"]["scoring_type"]
          dam_scoring_id?: string
          sung_at?: string
          total_score?: number
          pitch_score?: number | null
          stability_score?: number | null
          expression_score?: number | null
          vibrato_longtone_score?: number | null
          rhythm_score?: number | null
          ai_bonus?: number | null
          key_control?: number
          tempo_control?: number | null
          guide_melody?: boolean | null
          singing_range_lowest?: number | null
          singing_range_highest?: number | null
          vocal_range_lowest?: number | null
          vocal_range_highest?: number | null
          raw_xml?: Json
          created_at?: string
        };
        Relationships: [];
      };
      sessions: {
        Row: {
          id: string
          user_id: string
          started_at: string
          ended_at: string
          score_count: number
          avg_score: number | null
          max_score: number | null
          venue_name: string | null
          memo: string | null
          created_at: string
          updated_at: string
        };
        Insert: {
          id?: string
          user_id: string
          started_at: string
          ended_at: string
          score_count?: number
          avg_score?: number | null
          max_score?: number | null
          venue_name?: string | null
          memo?: string | null
          created_at?: string
          updated_at?: string
        };
        Update: {
          id?: string
          user_id?: string
          started_at?: string
          ended_at?: string
          score_count?: number
          avg_score?: number | null
          max_score?: number | null
          venue_name?: string | null
          memo?: string | null
          created_at?: string
          updated_at?: string
        };
        Relationships: [];
      };
      setlist_items: {
        Row: {
          id: string
          setlist_id: string
          user_id: string
          song_id: string
          position: number
          key_override: number | null
          note: string | null
          created_at: string
        };
        Insert: {
          id?: string
          setlist_id: string
          user_id: string
          song_id: string
          position: number
          key_override?: number | null
          note?: string | null
          created_at?: string
        };
        Update: {
          id?: string
          setlist_id?: string
          user_id?: string
          song_id?: string
          position?: number
          key_override?: number | null
          note?: string | null
          created_at?: string
        };
        Relationships: [];
      };
      setlists: {
        Row: {
          id: string
          user_id: string
          name: string
          description: string | null
          scheduled_for: string | null
          is_pinned: boolean
          created_at: string
          updated_at: string
        };
        Insert: {
          id?: string
          user_id: string
          name: string
          description?: string | null
          scheduled_for?: string | null
          is_pinned?: boolean
          created_at?: string
          updated_at?: string
        };
        Update: {
          id?: string
          user_id?: string
          name?: string
          description?: string | null
          scheduled_for?: string | null
          is_pinned?: boolean
          created_at?: string
          updated_at?: string
        };
        Relationships: [];
      };
      songs: {
        Row: {
          id: string
          title: string
          title_normalized: string | null
          artist: string
          artist_normalized: string | null
          request_no: string | null
          dam_contents_id: string | null
          vocal_range_lowest: number | null
          vocal_range_highest: number | null
          range_source: Database["public"]["Enums"]["range_source"] | null
          range_updated_at: string | null
          duration_sec: number | null
          genre: string | null
          created_at: string
          updated_at: string
        };
        Insert: {
          id?: string
          title: string
          title_normalized?: string | null
          artist: string
          artist_normalized?: string | null
          request_no?: string | null
          dam_contents_id?: string | null
          vocal_range_lowest?: number | null
          vocal_range_highest?: number | null
          range_source?: Database["public"]["Enums"]["range_source"] | null
          range_updated_at?: string | null
          duration_sec?: number | null
          genre?: string | null
          created_at?: string
          updated_at?: string
        };
        Update: {
          id?: string
          title?: string
          title_normalized?: string | null
          artist?: string
          artist_normalized?: string | null
          request_no?: string | null
          dam_contents_id?: string | null
          vocal_range_lowest?: number | null
          vocal_range_highest?: number | null
          range_source?: Database["public"]["Enums"]["range_source"] | null
          range_updated_at?: string | null
          duration_sec?: number | null
          genre?: string | null
          created_at?: string
          updated_at?: string
        };
        Relationships: [];
      };
      sync_logs: {
        Row: {
          id: string
          user_id: string
          started_at: string
          finished_at: string | null
          status: string
          scores_fetched: number | null
          scores_new: number | null
          error_message: string | null
          raw_response_path: string | null
        };
        Insert: {
          id?: string
          user_id: string
          started_at?: string
          finished_at?: string | null
          status: string
          scores_fetched?: number | null
          scores_new?: number | null
          error_message?: string | null
          raw_response_path?: string | null
        };
        Update: {
          id?: string
          user_id?: string
          started_at?: string
          finished_at?: string | null
          status?: string
          scores_fetched?: number | null
          scores_new?: number | null
          error_message?: string | null
          raw_response_path?: string | null
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
    Enums: {
      confidence_level: "practicing" | "normal" | "confident";
      range_source: "dam_ai" | "audio_analysis" | "manual";
      scoring_type: "ai" | "ai_heart" | "dxg" | "dx" | "other";
    };
  };
};
